/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.scu.oop.assign2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author prajakta
 */
public class Smartoven extends javax.swing.JFrame {


	Alpha2Oven oven=new Alpha2Oven();
	protected long startTime =System.currentTimeMillis();
	Timer t;
	boolean flag=true;




	/**
 * Creates new form NewJFrame
 */
public Smartoven() {
	initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
private void initComponents() {

	label1 = new java.awt.Label();
	jCheckBox1 = new javax.swing.JCheckBox();
	jLabel1 = new javax.swing.JLabel();
	jTextField1 = new javax.swing.JTextField();
	jComboBox1 = new javax.swing.JComboBox();
	Degree = new java.awt.Choice();
	jButton3 = new javax.swing.JButton();
	jPanel2 = new javax.swing.JPanel();
	jTextField3 = new javax.swing.JTextField();
	jLabel7 = new javax.swing.JLabel();
	jPanel1 = new javax.swing.JPanel();
	jLabel2 = new javax.swing.JLabel();
	jLabel3 = new javax.swing.JLabel();
	jButton1 = new javax.swing.JButton();
	tempF = new javax.swing.JTextField();
	jLabel4 = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	jButton2 = new javax.swing.JButton();
	jTextField5 = new javax.swing.JTextField();
	jSpinner1 = new javax.swing.JSpinner();
	jComboBox2 = new javax.swing.JComboBox();
	jSpinner2 = new javax.swing.JSpinner();
	jCheckBox2 = new javax.swing.JCheckBox();
	jLabel6 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	TempC = new javax.swing.JTextField();
	//        timer = new Timer(this);
	//        timer.setInitialDelay(pause);
	//        timer.start();

	label1.setText("label1");

	jCheckBox1.setText("jCheckBox1");

	jLabel1.setText("jLabel1");

	jTextField1.setText("jTextField1");

	jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
	jComboBox1.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			jComboBox1ActionPerformed(evt);
		}
	});


	javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	jPanel2.setLayout(jPanel2Layout);
	jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
			);
	jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
			);

	jTextField3.setText("jTextField3");

	jLabel7.setText("jLabel7");

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	jLabel2.setText("Oven Temperature");

	jLabel3.setText("Cooking Time in Minutes");

	jButton1.setText("Display Temperature");
	jButton1.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			jButton1ActionPerformed(evt);
		}
	});

	tempF.setEditable(false);

	jLabel4.setText("Place food");

	jLabel5.setText("Cooking time Left");

	jButton2.setText("Start");
	jButton2.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			jButton2ActionPerformed(evt);
		}
	});

	jTextField5.setEditable(false);

	jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

	jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celsius", "Fahrenheit" }));

	jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
	jSpinner2.setToolTipText("Set Cooking time in minutes\n");

	jCheckBox2.setText("yes");

	jLabel6.setText("Fahreheit:");

	jLabel8.setText("Celsius");

	javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(48, 48, 48)
									.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
											.addComponent(jLabel5)
											.addGroup(jPanel1Layout.createSequentialGroup()
													.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
															.addGroup(jPanel1Layout.createSequentialGroup()
																	.addComponent(jLabel4)
																	.addGap(127, 127, 127)
																	.addComponent(jCheckBox2))
																	.addGroup(jPanel1Layout.createSequentialGroup()
																			.addGap(192, 192, 192)
																			.addComponent(jLabel6)
																			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																			.addComponent(tempF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
																			.addGap(23, 23, 23)
																			.addComponent(jLabel8)
																			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																			.addComponent(TempC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
																			.addGroup(jPanel1Layout.createSequentialGroup()
																					.addGap(230, 230, 230)
																					.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																							.addComponent(jButton2)
																							.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
																							.addContainerGap(135, Short.MAX_VALUE))
																							.addGroup(jPanel1Layout.createSequentialGroup()
																									.addGap(34, 34, 34)
																									.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																											.addComponent(jButton1)
																											.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																													.addComponent(jLabel3)
																													.addComponent(jLabel2)))
																													.addGap(30, 30, 30)
																													.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																															.addComponent(jSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
																															.addComponent(jSpinner1))
																															.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																															.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																															.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);
	jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(29, 29, 29)
					.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(jPanel1Layout.createSequentialGroup()
									.addComponent(jLabel2)
									.addGap(32, 32, 32)
									.addComponent(jLabel3)
									.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
											.addGroup(jPanel1Layout.createSequentialGroup()
													.addGap(33, 33, 33)
													.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(tempF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jLabel6)
															.addComponent(jLabel8)
															.addComponent(TempC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
															.addGap(15, 15, 15))
															.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																	.addComponent(jButton1)
																	.addGap(18, 18, 18)))
																	.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																			.addGroup(jPanel1Layout.createSequentialGroup()
																					.addComponent(jLabel4)
																					.addGap(18, 18, 18)
																					.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																							.addComponent(jLabel5)
																							.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																							.addGroup(jPanel1Layout.createSequentialGroup()
																									.addGap(5, 5, 5)
																									.addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
																									.addGap(18, 18, 18)
																									.addComponent(jButton2))
																									.addGroup(jPanel1Layout.createSequentialGroup()
																											.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																													.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																													.addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																													.addGap(18, 18, 18)
																													.addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																													.addContainerGap(16, Short.MAX_VALUE))
			);

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					.addGap(0, 102, Short.MAX_VALUE)
					.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
			);
	layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addContainerGap())
			);

	pack();
}// </editor-fold>  
private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
	// TODO add your handling code here:
}                                          

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
	// TODO add your handling code here:
}                                          

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         


	displaytemperature();

}

private void displaytemperature() {


	String type=(String) (jComboBox2.getSelectedItem());
	double temp= (double) jSpinner1.getValue();
	if(type=="Fahrenheit")
	{

		oven.setTemperature(temp);

	}
	else
	{

		oven.setTemperatureInc(temp);

	}



	if(type=="Fahrenheit")
	{
		tempF.setText((Double.toString(temp)));
		System.out.println("" +oven.getTempinC());
		TempC.setText((Double.toString(this.oven.getTempinC())));

	}

	else    
	{
		TempC.setText(Double.toString(temp));
		tempF.setText(Double.toString(this.oven.getTempinF()));

	}

}                                        

// Handling click on start button 
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

	int cookingtime=(int) jSpinner2.getValue();
	double cookingtemperature=(double)jSpinner1.getValue();
	if(flag==true)
	{
		if(cookingtemperature<=0)
		{

			JOptionPane.showMessageDialog(null, "set the temperture");


		}
		else
		{

			if(cookingtime<=0)


			{

				JOptionPane.showMessageDialog(null, "set the time");
			}


			else
			{


				if(!jCheckBox2.isSelected())
				{

					JOptionPane.showMessageDialog(null, "place the food");

				}


				else
				{

					t = new javax.swing.Timer(1000, new clock());

					t.start();

				}
			}

		}

	}

}
class clock implements ActionListener

{  
	int mealtime =(int) jSpinner2.getValue();
	int count=(mealtime*60);
	@Override

	public void actionPerformed(ActionEvent e) {

		// TODO Auto-generated method stub

		
		int m = count/60;
		int s = count%60;
		count--;
		if(count==-2)

		{

			flag = true;          

			t.stop();

		
		}

		else{

			flag=false;    

			jTextField5.setText("" + m + ":" + s);
		}
	}

}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				javax.swing.UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	} catch (ClassNotFoundException ex) {
		java.util.logging.Logger.getLogger(Smartoven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
		java.util.logging.Logger.getLogger(Smartoven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
		java.util.logging.Logger.getLogger(Smartoven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		java.util.logging.Logger.getLogger(Smartoven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
		public void run() {
			new Smartoven().setVisible(true);
		}
	});
}

// Variables declaration - do not modify                     
private java.awt.Choice Degree;
private javax.swing.JTextField TempC;
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JButton jButton3;
private javax.swing.JCheckBox jCheckBox1;
private javax.swing.JCheckBox jCheckBox2;
private javax.swing.JComboBox jComboBox1;
private javax.swing.JComboBox jComboBox2;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JPanel jPanel1;
private javax.swing.JPanel jPanel2;
private javax.swing.JSpinner jSpinner1;
private javax.swing.JSpinner jSpinner2;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField3;
private javax.swing.JTextField jTextField5;
private java.awt.Label label1;
private javax.swing.JTextField tempF;
// End of variables declaration                   
}

